version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - "${PGDATA}:/var/lib/postgresql/data" 
  server:
    build:
      context: .
      dockerfile: deploy/server/server.dockerfile      
    command: bash -c "python backend/manage.py migrate && gunicorn --chdir backend wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./../data:/data
      - ./../media:/media
    expose:
      - "8000"
    depends_on:
      - db      
    restart: unless-stopped
    user: 1000:1000

  nginx:
    image: nginx:alpine
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - .:/app
      - ./deploy/server/nginx.conf:/etc/nginx/conf.d/server.conf
    depends_on:
      - server
    restart: unless-stopped
