- name: Create data directory 
  file: 
    path: "{{ ansible_env.PWD }}/data"
    state: directory
  become: no     

- name: Create media directory 
  file: 
    path: "{{ ansible_env.PWD }}/media"
    state: directory
  become: no      
    

- name: Shutdown server using docker compose
  shell: "SERVER_PORT=9000 docker-compose -f pediatryAd/deploy/server/docker-compose.yml --project-directory pediatryAd down"

- name: Start server using docker compose
  shell: "SERVER_PORT=9000 docker-compose -f pediatryAd/deploy/server/docker-compose.yml --project-directory pediatryAd up --build -d"

  




